### 6/13/13
### accompanies runfubar_rescol.py, run_rescol.sh
### sed clustal/mafft/linsi to switch aligner and directories

#!/bin/bash
#$ -N fuclustal
#$ -e efuclustal
#$ -o ofuclustal
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-9:1
#$ -pe serial 2

source ~/.bashrc

BASEDIR="shortindel_16p"


# Create Working Directory and remove anything that might have been there woops!
RDIR=/home/sjs3495/clustal_fubar/
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR



# Copy Data and Config Files
cp /home/sjs3495/runfubar_rescol.py .
cp -r /home/sjs3495/current/fubar/FUBARmaterials .

# Command to run
sed -i "s/placeholder/$JOB_NAME-$JOB_ID-$SGE_TASK_ID/g" FUBARmaterials/autoFUBAR.bf
module load python
pwd
python runfubar_rescol.py $SGE_TASK_ID $BASEDIR clustal

# Copy Results Back to Home Directory
cp -r fubar_* $RDIR

# Cleanup
rm -rf $WDIR
