### 6/13/13
### accompanies runfubar_rescol.py, run_rescol.sh
### sed clustal/mafft/linsi to switch aligner and directories

#!/bin/bash
#$ -N clustal_paml
#$ -e e_clustal_paml
#$ -o o_clustal_paml
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-5:1

source ~/.bashrc

BASEDIR="shortindel_16p"

# Create Working Directory and remove anything that might have been there woops!
RDIR=/home/sjs3495/clustal_paml/
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $RDIR
mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR



# Copy Data and Config Files
cp /home/sjs3495/paml.py .
cp /home/sjs3495/codeml.ctl .

# Command to run
module load python
pwd
python paml.py $SGE_TASK_ID $BASEDIR clustal

# Copy Results Back to Home Directory
cp -r paml_* $RDIR

# Cleanup
rm -rf $WDIR
