## Tweaked 3/29/14


#!/bin/bash
#$ -N fubarCPU
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1
#$ -pe serial 5

CPU=5
GENE=rho
ALNDIR=/home/sjs3495/alntree_neutral/nucguided_$GENE
TREEDIR=/home/sjs3495/alntree_neutral/aatrees_$GENE
RDIR=/home/sjs3495/fubar_neutral

source ~/.bashrc

# Create Working Directory and remove anything that might have been there woops!
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $RDIR
mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR



# Copy Data and Config Files
cp -r /home/sjs3495/stuff_aln_project/FUBARmaterials .
cp /home/sjs3495/alignment_filtering/scripts/cluster/fubar.py .

# Command to run
sed -i "s/placeholder/$JOB_NAME-$JOB_ID-$SGE_TASK_ID/g" FUBARmaterials/autoFUBAR.bf
module load python
pwd
python fubar.py $SGE_TASK_ID $GENE $ALNDIR $TREEDIR $CPU

# Cleanup
cp -r fubar_* $RDIR
rm -rf $WDIR
