## Tweaked 3/29/14, 4/1/14.


#!/bin/bash
#$ -N fubar
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-1:1
#$ -pe serial 16


CPU=15
DATASET=GP41    # HA or GP41

## Run-specific settings
GENE=or5       # or5, rho, prk, flat
MASK=50        # 30, 50, 70, 90
ALG=refaln   # Guidance, GuidanceP, BMweights, BMweightsP, PDweights, PDweightsP
NUM=`expr $SGE_TASK_ID - 1` # Rep number. Since I index from 0 but array jobs from 1, must -1 from task id



# Alignment file name
if [ $ALG == "refaln" ]; then
	ALN=$ALG$NUM.fasta
else
	ALN=${ALG}_${MASK}_${NUM}.fasta
fi

# Set up directories
ALNDIR=/home/sjs3495/ALNPAPER_RESULTS/$DATASET/alntree/nucguided_$GENE
TREEDIR=/home/sjs3495/ALNPAPER_RESULTS/$DATASET/alntree/aatrees_$GENE
RDIR=/home/sjs3495/FUBARTEST
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $RDIR
mkdir -p $WDIR
if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi

cd $WDIR

# Copy fubar files
cp -r /home/sjs3495/bin/HBL/FUBAR/* .
cp -r /home/sjs3495/alignment_filtering/scripts/selection_inference/autoFUBAR.bf .
cp /home/sjs3495/bin/bin/HYPHYMP .

# Copy data files
cp $ALNDIR/$ALN temp.fasta
cp $TREEDIR/aatree$NUM.txt tree.tre
ls
head autoFUBAR.bf

# Format the fubar file and run
sed -i "s/placeholder/$JOB_NAME-$JOB_ID-$SGE_TASK_ID/g" autoFUBAR.bf
head autoFUBAR.bf
./HYPHYMP autoFUBAR.bf CPU=$CPU

# Save the output files to their appropriate names
mkdir fubar
mkdir grid
mkdir prior
mv tree.tre.fubar.csv fubar/$ALN.fubar
mv tree.tre.grid_info grid/$ALN.grid
mv tree.tre.priorMean prior/$ALN.prior

# Cleanup
cp -r fubar $RDIR
cp -r grid $RDIR
cp -r prior $RDIR
rm -rf $WDIR
