## redone on 12/13/13 to run mask50 for the prk non-penal methods ONLY.


#!/bin/bash
#$ -N paml
#$ -e e_paml
#$ -o o_paml
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 80-80:1

source ~/.bashrc
ALG=guidance
GENE=prk
MASK=30_


# Create Working Directory and remove anything that might have been there woops!
RDIR=/home/sjs3495/paml_prk_3090
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

#mkdir -p $RDIR
mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created. BUMMER.
  exit
fi
cd $WDIR



# Copy Data and Config Files
cp  /home/sjs3495/codeml.ctl .
cp /home/sjs3495/paml.py .

# Command to run
module load python
pwd
python paml.py $SGE_TASK_ID $ALG $GENE $MASK

# Cleanup
cp -r paml_* $RDIR
rm -rf $WDIR
