## Tweaked 3/30/14


#!/bin/bash
#$ -N paml
#$ -e e_$JOB_NAME
#$ -o o_$JOB_NAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1

source ~/.bashrc

### Define run conditions ###
GENE=rho
MASK=50
ALG=Guidance
NUM=`expr $SGE_TASK_ID - 1`

if [ $ALG == "refaln" ]; then
	ALN=$ALG$NUM.fasta
else
	ALN=${ALG}_${MASK}_${NUM}.fasta
fi

ALNDIR=/home/sjs3495/alntree_neutral/nucguided_$GENE
TREEDIR=/home/sjs3495/alntree_neutral/aatrees_$GENE
RDIR=/home/sjs3495/paml_neutral
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $RDIR
mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created. BUMMER.
  exit
fi
cd $WDIR

# Copy over files to run with.  Includes control file, executable, alignment, and tree
cp  /home/sjs3495/alignment_filtering/scripts/selection_inference/codeml.ctl .
cp /home/sjs3495/bin/codeml .
cp $ALNDIR/$ALN temp.fasta
cp $TREEDIR/aatree$NUM.txt tree.tre

# Run paml
./codeml codeml.ctl

# Save the final paml file
mv rst $RDIR/$ALN.rst

# Delete everything
rm -rf $WDIR
















