# 8/6/13

#!/bin/bash
#$ -N truepaml
#$ -e e_$JOBNAME
#$ -o o_$JOBNAME
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1

source ~/.bashrc

DATASET=HA     # HA or GP41
GENE=or5       # or5, rho, prk, flat
NUM=`expr $SGE_TASK_ID - 1` # Rep number. Since I index from 0 but array jobs from 1, must -1 from task id
ALN=truealn_codon${NUM}.fasta
OUTFILE=truealn$NUM.fasta.rst ## have 2 extensions for consistency with inferred alignment files


ALNDIR=/home/sjs3495/ALNPAPER_RESULTS/$DATASET/simseqs/$GENE
TREEDIR=/home/sjs3495/ALNPAPER_RESULTS/trees
RDIR=/home/sjs3495/ALNPAPER_RESULTS/$DATASET/fubar/fubar_$GENE
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $RDIR
mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR


# Copy paml files
cp  /home/sjs3495/alignment_filtering/scripts/selection_inference/codeml.ctl .
cp /home/sjs3495/bin/codeml .

# Copy data files
cp $ALNDIR/$ALN temp.fasta
cp $TREEDIR/$GENE.txt tree.tre

# Run paml
./codeml codeml.ctl

# rename output file
mv rst $OUTFILE

# Save and cleanup
cp $OUTFILE $RDIR
rm -rf $WDIR

