# 8/6/13

#!/bin/bash
#$ -N truepaml
#$ -e e_truepaml
#$ -o o_truepaml
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1
#$ -pe serial 1

DIR=seqs_a
GENE=or5

source ~/.bashrc

# Create Working Directory and remove anything that might have been there woops!
RDIR=/home/sjs3495/truepaml_HA
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $RDIR
mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR



# Copy Data and Config Files
cp -r /home/sjs3495/codeml.ctl .
cp /home/sjs3495/truepaml.py .

# Command to run
module load python
pwd
python truepaml.py $SGE_TASK_ID $GENE $DIR

# Cleanup
cp -r truepaml_* $RDIR
rm -rf $WDIR
