# 8/6/13

#!/bin/bash
#$ -N truefu
#$ -e e_truefu
#$ -o o_truefu
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-100:1
#$ -pe serial 2

DIR=seqs_a
GENE=prk

source ~/.bashrc

# Create Working Directory and remove anything that might have been there woops!
RDIR=/home/sjs3495/truefu_HA
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $RDIR
mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR



# Copy Data and Config Files
cp -r /home/sjs3495/FUBARmaterials .
cp /home/sjs3495/truefu.py .

# Command to run
sed -i "s/placeholder/$JOB_NAME-$JOB_ID-$SGE_TASK_ID/g" FUBARmaterials/autoFUBAR.bf
module load python
pwd
python truefu.py $SGE_TASK_ID $GENE $DIR

# Cleanup
cp -r truefu_* $RDIR
rm -rf $WDIR
