### 6/13/13
### accompanies apply_optimal.py, run_optimal.sh
### sed clustal/mafft/linsi to switch aligner

#!/bin/bash
#$ -N optaln
#$ -e e_optaln
#$ -o o_optaln
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-24:1
#$ -pe serial 2

source ~/.bashrc

# Create Working Directory and remove anything that might have been there woops!
RDIR=/home/sjs3495/optimal_alntree/
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR



# Copy Data and Config Files
cp /home/sjs3495/apply_optimal.py .
cp /home/sjs3495/current/aligning/tools/guidance_score .

# Command to run
export OMP_NUM_THREADS=2
module load python
pwd
python runfubar_rescol.py $SGE_TASK_ID clustal

# Copy Results Back to Home Directory
cp -r optimal_* $RDIR

# Cleanup
rm -rf $WDIR
