### 6/16/13
### accompanies custom_runfubar_rescol.py, custom_run_rescol.sh
### THIS IS USED FOR THE ISSUES ARISING FROM MISSING TREES!! ONLY!!

#!/bin/bash
#$ -N fulinsi
#$ -e efulinsi
#$ -o ofulinsi
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -pe serial 2

source ~/.bashrc



# Create Working Directory and remove anything that might have been there woops!
RDIR=/home/sjs3495/linsi_fubar/
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID

mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR



# Copy Data and Config Files
cp /home/sjs3495/custom_fubar_rescol.py .
cp -r /home/sjs3495/current/fubar/FUBARmaterials .

# Command to run
sed -i "s/placeholder/$JOB_NAME-$JOB_ID/g" FUBARmaterials/autoFUBAR.bf
module load python
pwd
python custom_fubar_rescol.py

# Copy Results Back to Home Directory
cp -r fubar_* $RDIR

# Cleanup
rm -rf $WDIR
