
#!/bin/bash
#$ -N mafftredo
#$ -e e_mafftredo
#$ -o o_mafftredo
#$ -S /bin/bash
#$ -q wilke
#$ -m beas
#$ -t 1-12:1
#$ -pe serial 4

source ~/.bashrc

# Create Working Directory and remove anything that might have been there woops!
RDIR=/home/sjs3495/mafft_alntree/
WDIR=/state/partition1/sjs3495/$JOB_NAME-$JOB_ID-$SGE_TASK_ID

mkdir -p $WDIR

if [ ! -d $WDIR ]
then
  echo $WDIR not created
  exit
fi
cd $WDIR



# Copy Data and Config Files
cp /home/sjs3495/run_alntree_mafft_REDO.py .
cp -r /home/sjs3495/current/aligning/tools/* .

# Command to run
export OMP_NUM_THREADS=4
module load python
pwd
python run_alntree_mafft_REDO.py $SGE_TASK_ID

# Copy Results Back to Home Directory
cp -r aaguided_* $RDIR
cp -r nucguided_* $RDIR
cp -r aatrees_* $RDIR

# Cleanup
rm -rf $WDIR
